### ISSUE TITLE
Do not accept a second use of a valid OTP code

### ISSUE THREAD

**Issue by victorlap** [DarkGhostHunter/Laraguard#1]
First and foremost, I would like to thank you for creating such a nice project. I want to implement this in an app but stumbled accross the following piece in the [TOTP RFC](https://tools.ietf.org/html/rfc6238#section-5): 

>    Note that a prover may send the same OTP inside a given time-step
   window multiple times to a verifier.  The verifier MUST NOT accept
   the second attempt of the OTP after the successful validation has
   been issued for the first OTP, which ensures one-time only use of an
   OTP.

Maybe it is feasible to cache the usage of a token and only allow the first submission to pass through?

**Comment by DarkGhostHunter** [comment]
Thanks. Since it's a very variable thing, a Cache could be better.

![image](https://user-images.githubusercontent.com/5141911/74107023-ba17b380-4b4a-11ea-9a50-9305bdc756c7.png)

I will consider this as a security problem, because an attacker could spy the code and use it again. I will take down the package from packagist until this is resolved.

**Comment by DarkGhostHunter** [comment]
I resolved it locally. Basically, a trait initialized the cache and then saves the code until the time it expires.

Need more testing, but I plan to release it this week.

**Comment by DarkGhostHunter** [comment]
Fixed in #2

**Comment by victorlap** [comment]
Impressed by the speedy resolution!🙌

**Comment by DarkGhostHunter** [comment]
> I am impressed by the speedy resolution!🙌

Thanks. Any new idea hit the issues.
